kind: Deployment
apiVersion: apps/v1
metadata:
  name: blue-v1-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
       - name: app
         image: leaddevops/kubeserve:v1
