kind: Service
apiVersion: v1
metadata:
  name: svc2
spec:
  type: NodePort  ## it exposes a NodePort / HostPort on every node in the cluster and also create virtual Loadbalncer(clusterip) that forwards the request into mutiple backend pods
  selector:
    role: db
  ports:
    - port: 80   # Virtual LB port, you can define any port of your choice
      targetPort: 3000   ## port number inside container
      #nodePort: 30005
